apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: argocd
    helm:
      values: |-
        dex:
          enabled: false
        applicationSet:
          enabled: false
        notifications:
          enabled: false
        server:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              nginx.ingress.kubernetes.io/backend-protocol: HTTPS
            ingressClassName: nginx
            hosts:
              - argocd.workshop.jsleague.ro
            paths:
              - /
            pathType: ImplementationSpecific
            tls:
              - secretName: argocd.workshop.jsleague.ro-tls
                hosts:
                  - argocd.workshop.jsleague.ro
            https: true
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.6.2
