apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: cert-manager
    helm:
      values: |-
        global:
          leaderElection:
            namespace: cert-manager
        installCRDs: true
        prometheus:
          enabled: false
    repoURL: https://charts.jetstack.io
    targetRevision: 1.9.1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
