apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: ingress-nginx
    helm:
      values: |-
        controller:
          hostPort:
            enabled: true
          publishService:
            enabled: false
          extraArgs:
            publish-status-address: 138.201.92.128
            update-status: ""
          kind: DaemonSet
          tolerations:
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
          nodeSelector: {}
          service:
            type: ClusterIP
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.2.3
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
