apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-cluster
  namespace: argocd
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: rook-ceph-cluster
    repoURL: git@github.com:lbogdan/k8s-workshop-infra.git
    targetRevision: HEAD
