apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  destination:
    namespace: rook-ceph
    server: https://kubernetes.default.svc
  project: infra
  source:
    chart: rook-ceph
    helm:
      values: |-
        csi:
          pluginTolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
    repoURL: https://charts.rook.io/release
    targetRevision: 1.9.9
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
