apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# taken from https://github.com/lbogdan/kubelet-rubber-stamp/tree/master/deploy
resources:
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
